site.name: Our Family Site
host.name: your-app-id.appspot.com
secret.key: e.g. >>> import os; os.urandom(24)

messageboard.email.from: Our Family
messageboard.email.address: admin@your-app-id.appspot.com

features.wishlists: True
features.login.firstname: False

instagram.client.id: changeme
instagram.client.secret: changeme
facebook.app.id: changeme
facebook.app.secret: changeme

# To get access_token, go here:
# https://graph.facebook.com/oauth/access_token?client_id={client.id}&client_secret={client.secret}&grant_type=client_credentials
facebook.access.token: changeme


# In DEBUG mode, anything under local.settings overrides existing settings with the same name;
#   when not in DEBUG mode, all local.settings are ignored
local.settings:
  host.name: localhost:8080
  instagram.client.id: changeme
  instagram.client.secret: changeme
  facebook.app.id: changeme
  facebook.app.secret: changeme
  facebook.access.token: changeme
